#!/bin/bash

DAEMON=cwProbe
NAME=cwProbe
DESC="CloudWave Probe"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

exec="/usr/bin/cwProbe"
#logfile="/var/log/cloudwave/cwProbe.log"


case "$1" in
start)
	printf "%-30s" "Starting $NAME..."
	PID=`$exec > /dev/null 2>&1 & echo $!`
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail!"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "OK!"
        fi
;;
status)
        printf "%-30s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists!"
            else
                echo "Running!"
            fi
        else
            printf "%s\n" "Service not running!"
        fi
;;
stop)
        printf "%-30s" "Stopping $NAME"
            PID=`cat $PIDFILE`
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "OK!"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found!"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
